# Schema: https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/master/service-schema.json

trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: InstallHelloWorld@0
  inputs:
    version: '0.0.1'
- task: RunHelloWorldApp@0